api_platform:
    title: 'MMC Connect API'
    version: '1.0.0'
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
    collection:
        exists_parameter_name: 'exists'
        order: 'ASC'
        order_parameter_name: 'order'
        pagination:
            enabled: true
            client_enabled: true
            client_items_per_page: true
            items_per_page: 10
            maximum_items_per_page: 30
            page_parameter_name: 'page'
            enabled_parameter_name: 'pagination'
            items_per_page_parameter_name: 'itemsPerPage'
            partial: false
            client_partial: false
            partial_parameter_name: 'partial'
